var something = new Date();
console.log("25", something.toLocaleTimeString());
console.log("1", something.getTime());
console.log("2", something.getFullYear());
console.log("3", something.getDay());
console.log("4", something.getDate());
console.log("5", something.getMonth());
console.log("6", something.getHours());
console.log("7", something.getMilliseconds());
console.log("8", something.getSeconds());
console.log("9", something.getTimezoneOffset());
console.log("10", something.toISOString());
console.log("11", something.getUTCDate());
console.log("12", something.getUTCFullYear);
console.log("13", something.getUTCDay());
console.log("14", something.getUTCHours());
console.log("15", something.getUTCMilliseconds());
console.log("16", something.getUTCMonth());
console.log("17", something.getUTCSeconds());

console.log("19", something.toDateString());
console.log("21", something.toISOString());
console.log("22", something.toTimeString());
console.log("23", something.toString());
console.log("24", something.toJSON());
console.log("25", something.toUTCString());
console.log("25", something.toLocaleTimeString());
